name: Docker Image CI

on:
  push:
    tags:
      - '*'   # Matches any tag
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v4
    
        - name: Set dynamic tag
          run: echo "TAG_DATE=$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV
    
        # התחברות ישירה ל-Docker Hub באמצעות ה-Secrets שלך
        - name: Login to Docker Hub
          run: echo "${{ secrets.DEVOPS_TEAM_PASSWORD }}" | docker login -u "${{ secrets.DEVOPS_TEAM_USERNAME }}" --password-stdin
    
        # בניית האימג' עם השם המלא של ה-Repository שלך ב-Docker Hub
        - name: Build the Docker image
          run: |
            docker build . \
              --file Dockerfile \
              --tag ${{ secrets.DEVOPS_TEAM_USERNAME }}/fedora_dev:$GITHUB_REF_NAME \
              --tag ${{ secrets.DEVOPS_TEAM_USERNAME }}/fedora_dev:latest
    
        # דחיפה (Push) של האימג' ל-Docker Hub
        - name: Push Docker image
          run: |
            #docker push ${{ secrets.DEVOPS_TEAM_USERNAME }}/fedora_dev:$GITHUB_REF_NAME
            #docker push ${{ secrets.DEVOPS_TEAM_USERNAME }}/fedora_ev:latest
